# Project information
site_name: Ragdoll Dynamics | Real-time physics for Autodesk Maya 2020
site_description: Ragdoll enables animators to work directly with live physics in their character rigs, at a 0-5 ms per frame performance impact.
site_author: Imbalance
site_url: https://ragdolldynamics.com

# Copyright
copyright: "Copyright &copy; 2021 Imbalance"

theme:
    name: null
    custom_dir: 'theme/'

docs_dir: pages

# Options
extra:
  logo: assets/img/logo.png
  favicon: assets/img/favicon

  # Where to go in case the user does not have JavaScript enabled
  no_javascript_url: https://learn.ragdolldynamics.com/no-javascript/

  social:
    - type: globe
      link: https://ragdolldynamics.com
    - type: github-alt
      link: https://github.com/mottosso/ragdoll
    - type: linkedin
      link: https://linkedin.com/in/ragdolldynamics

# Extensions
markdown_extensions:
  - markdown.extensions.extra

plugins:
  - mkdocs-ragdoll
