name: Ragbuild

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    # Setup mkdocs
    - run: python -m pip install mkdocs libsass

    # Build
    - run: PYTHONPATH=$(pwd)/plugins mkdocs build
    - run: cp ./CNAME ./site/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages  # deploying branch
